"""Node and Telemetry Beanie Document Models."""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from beanie import Document, Indexed
from pydantic import Field
import pymongo


class Node(Document):
    id: str = Field(..., description="Node ID: node_...")
    workspace_id: Indexed(str) = Field(...)
    name: str = Field(..., min_length=1, max_length=100)
    hostname: Optional[str] = Field(default=None)
    ip_address: Optional[str] = Field(default=None, description="Primary reported IP address")
    description: Optional[str] = Field(default=None)
    os: Optional[str] = Field(default=None)
    arch: Optional[str] = Field(default=None)
    enabled: bool = Field(default=True)
    status: str = Field(default="UNKNOWN", description="OPERATIONAL, STALE, OFFLINE, UNKNOWN")
    activation_status: str = Field(
        default="PENDING_ACTIVATION",
        description="PENDING_ACTIVATION, ACTIVE, REVOKED",
    )
    last_reported_at: Optional[datetime] = Field(
        default=None,
        description="Reported timestamp from node clock",
    )
    last_received_at: Optional[datetime] = Field(
        default=None,
        description="Authoritative timestamp generated by Master",
    )
    latest_metrics: Optional[Dict[str, Any]] = Field(default_factory=dict)
    latest_docker: Optional[List[Dict[str, Any]]] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Settings:
        name = "nodes"
        indexes = [
            [("workspace_id", pymongo.ASCENDING), ("id", pymongo.ASCENDING)],
            [("workspace_id", pymongo.ASCENDING), ("status", pymongo.ASCENDING)],
            [("last_received_at", pymongo.DESCENDING)],
        ]


class NodeActivation(Document):
    id: str = Field(...)
    token_hash: Indexed(str, unique=True) = Field(..., description="SHA-256 of raw activation token")
    workspace_id: Indexed(str) = Field(...)
    node_id: Indexed(str) = Field(...)
    expires_at: datetime = Field(...)
    consumed_at: Optional[datetime] = Field(default=None)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Settings:
        name = "node_activations"
        indexes = [
            [("token_hash", pymongo.ASCENDING)],
            [("node_id", pymongo.ASCENDING)],
            [("expires_at", pymongo.ASCENDING)],
        ]


class NodeCredential(Document):
    id: str = Field(...)
    workspace_id: Indexed(str) = Field(...)
    node_id: Indexed(str) = Field(...)
    secret_hash: str = Field(..., description="Salted HMAC-SHA256 of node permanent secret")
    revoked: bool = Field(default=False)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    revoked_at: Optional[datetime] = Field(default=None)

    class Settings:
        name = "node_credentials"
        indexes = [
            [("workspace_id", pymongo.ASCENDING), ("node_id", pymongo.ASCENDING)],
            [("node_id", pymongo.ASCENDING), ("revoked", pymongo.ASCENDING)],
        ]


class NodeMetric(Document):
    id: str = Field(...)
    workspace_id: Indexed(str) = Field(...)
    node_id: Indexed(str) = Field(...)
    received_at: Indexed(datetime) = Field(description="Authoritative Master timestamp")
    reported_at: datetime = Field(description="Node clock timestamp")
    ip_address: Optional[str] = Field(default=None)
    cpu_usage: float = Field(default=0.0)
    memory_used: int = Field(default=0)
    memory_total: int = Field(default=0)
    disk_used: int = Field(default=0)
    disk_total: int = Field(default=0)
    uptime_seconds: int = Field(default=0)
    docker_containers: List[Dict[str, Any]] = Field(default_factory=list)

    class Settings:
        name = "node_metrics"
        indexes = [
            [("workspace_id", pymongo.ASCENDING), ("node_id", pymongo.ASCENDING), ("received_at", pymongo.DESCENDING)],
            [("node_id", pymongo.ASCENDING), ("received_at", pymongo.DESCENDING)],
        ]
